### ISSUE TITLE
Support for Go and Ruby

### ISSUE THREAD

**Issue by pwntester** [zbazztian/gh-tailor#1]
Thanks for this extension @zbazztian it looks really useful to bootstrap new packs. I tried it with:

```
gh tailor init -l go -b "codeql/go-all" -n "pwntester/grafana_va" variant_analysis
```

and got:

```
Traceback (most recent call last):
  File "/Users/pwntester/.local/share/gh/extensions/gh-tailor/cli.py", line 592, in <module>
    main()
  File "/Users/pwntester/.local/share/gh/extensions/gh-tailor/cli.py", line 584, in main
    args.func(args)
  File "/Users/pwntester/.local/share/gh/extensions/gh-tailor/cli.py", line 60, in init
    util.tailor_template(
  File "/Users/pwntester/.local/share/gh/extensions/gh-tailor/util.py", line 64, in tailor_template
    shutil.copyfile(
  File "/Users/pwntester/.pyenv/versions/3.8.9/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pwntester/.local/share/gh/extensions/gh-tailor/templates/go/settings.yml'
```

It seems there are no templates yet for Go and Ruby. Not urgent at all, but would be nice to add them in the future! 

Thanks!

**Comment by zbazztian** [comment]
@pwntester I just added those, so it should work now.
I also added some more documentation in the README.

**Comment by pwntester** [comment]
awesome, thanks!
